//Basta dar Send Requests para testar
//Alterar id do video no fim da rota para alterar e deletar
//Conferir alterações no "Postgres Web" -> Neon.tech

POST https://node-do-zero-hequ.onrender.com/videos
Content-Type: application/json

{
    "title": "Video node",
    "description": "Esse é o primeiro video",
    "duration": 180
}

###

GET https://node-do-zero-hequ.onrender.com/videos
//GET https://node-do-zero-hequ.onrender.com/videos?search=node

###

PUT https://node-do-zero-hequ.onrender.com/videos/6409d8ab-e5db-495b-b19d-449f036f2a08
Content-Type: application/json

{
    "title": "Video 02",
    "description": "Esse é o primeiro video",
    "duration": 180
}

###

DELETE https://node-do-zero-hequ.onrender.com/videos/4e630363-8a7e-4eec-ba95-8435c5c758f4